### ISSUE TITLE
docker run -v /mnt/d/chendi/output:/output -v /mnt/d/chendi/dolt:/dolt -it --rm chenditc/investment_data bash dump_qlib_bin.sh && cp ./qlib_bin.tar.gz /output/ 执行到python3 ./qlib/normalize.py normalize_data 说找不到data_collector

### ISSUE THREAD

**Issue by berisfu** [chenditc/investment_data#50]
Dumping to file:  /investment_data/qlib/qlib_source/SZ301611.csv
Dumping to file:  /investment_data/qlib/qlib_source/SZ301618.csv
Dumping to file:  /investment_data/qlib/qlib_source/SZ399300.csv
+ export PYTHONPATH=:/qlib/scripts
+ PYTHONPATH=:/qlib/scripts
+ python3 ./qlib/normalize.py normalize_data --source_dir ./qlib/qlib_source/ --normalize_dir ./qlib/qlib_normalize --max_workers=16 --date_field_name=tradedate
============
ATTENTION: Need to put qlib/scripts directory into PYTHONPATH
============
Traceback (most recent call last):
  File "/investment_data/./qlib/normalize.py", line 11, in <module>
    raise e
  File "/investment_data/./qlib/normalize.py", line 5, in <module>
    from data_collector.base import Normalize
ModuleNotFoundError: No module named 'data_collector'

**Comment by berisfu** [comment]
完整的日志如下：
/mnt/d/chendi$ docker run -v /mnt/d/chendi/output:/output -v /mnt/d/chendi/dolt:/dolt -it --rm chenditc/investment_data bash dump_qlib_bin.sh && cp ./qlib_bin.tar.gz /output/
Unable to find image 'chenditc/investment_data:latest' locally
latest: Pulling from chenditc/investment_data
Digest: sha256:c185e1fa93a388ba6c59ab7524e14211b9bba1b9d351348f13592a6b3f719a21
Status: Downloaded newer image for chenditc/investment_data:latest
+ WORKING_DIR=
+ QLIB_REPO=https://github.com/microsoft/qlib.git
+ command -v dolt
+ mkdir -p /dolt
+ '[' '!' -d /dolt/investment_data ']'
+ cd /dolt
+ dolt clone chenditc/investment_data
cloning https://doltremoteapi.dolthub.com/chenditc/investment_data
+ '[' '!' -d /qlib ']'
+ git clone https://github.com/microsoft/qlib.git
Cloning into 'qlib'...
remote: Enumerating objects: 18253, done.
remote: Counting objects: 100% (721/721), done.
remote: Compressing objects: 100% (371/371), done.
remote: Total 18253 (delta 460), reused 522 (delta 345), pack-reused 17532 (from 1)
Receiving objects: 100% (18253/18253), 17.03 MiB | 3.95 MiB/s, done.
Resolving deltas: 100% (13173/13173), done.
Updating files: 100% (609/609), done.
+ cd /dolt/investment_data
+ dolt pull origin
- Pulling...Fast-forward
Updating o61u0gvd8mj532vcffvgt835bvji1r79..bec1m9b6vqaveln0u34aafqodek5jtog
/ Pulling...final_a_stock_eod_price | 1649772 -----------------------------
ts_a_stock_eod_price    | 1650441 *-----------------------------
ts_index_weight         | 123274  --
ts_link_table           | 211     -
ts_trade_day_calendar   | 366     -
5 tables changed, 0 rows added(+), 390 rows modified(*), 3423674 rows deleted(-)
+ sleep 5s
+ dolt sql-server
Starting server with Config HP="localhost:3306"|T="28800000"|R="false"|L="info"|S="/tmp/mysql.sock"
INFO[0002] Server ready. Accepting connections.
WARN[0002] secure_file_priv is set to "", which is insecure.
WARN[0002] Any user with GRANT FILE privileges will be able to read any file which the sql-server process can read.
WARN[0002] Please consider restarting the server with secure_file_priv set to a safe (or non-existent) directory.
+ cd /investment_data
+ mkdir -p ./qlib/qlib_source
+ python3 ./qlib/dump_all_to_qlib_source.py
INFO[0006] NewConnection                                 DisableClientMultiStatements=false connectionID=1
/investment_data/./qlib/dump_all_to_qlib_source.py:10: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  stock_df = pd.read_sql("select *, amount/volume*10 as vwap from final_a_stock_eod_price", dbConnection)
INFO[0724] ConnectionClosed                              connectionID=1
Dumping to file:  /investment_data/qlib/qlib_source/BJ430017.csv
Dumping to file:  /investment_data/qlib/qlib_source/BJ430047.csv
Dumping to file:  /investment_data/qlib/qlib_source/BJ430090.csv
Dumping to file:  /investment_data/qlib/qlib_source/BJ430139.csv
....................................................
....................................................
Dumping to file:  /investment_data/qlib/qlib_source/SZ301606.csv
Dumping to file:  /investment_data/qlib/qlib_source/SZ301607.csv
Dumping to file:  /investment_data/qlib/qlib_source/SZ301608.csv
Dumping to file:  /investment_data/qlib/qlib_source/SZ301611.csv
Dumping to file:  /investment_data/qlib/qlib_source/SZ301618.csv
Dumping to file:  /investment_data/qlib/qlib_source/SZ399300.csv
+ export PYTHONPATH=:/qlib/scripts
+ PYTHONPATH=:/qlib/scripts
+ python3 ./qlib/normalize.py normalize_data --source_dir ./qlib/qlib_source/ --normalize_dir ./qlib/qlib_normalize --max_workers=16 --date_field_name=tradedate
============
ATTENTION: Need to put qlib/scripts directory into PYTHONPATH
============
Traceback (most recent call last):
  File "/investment_data/./qlib/normalize.py", line 11, in <module>
    raise e
  File "/investment_data/./qlib/normalize.py", line 5, in <module>
    from data_collector.base import Normalize
ModuleNotFoundError: No module named 'data_collector'

**Comment by berisfu** [comment]
脚本调整了一下，可以了，谢谢。

**Comment by berisfu** [comment]
已解决
